Octopus internal review
norikdoo/zephyr pull request #1
Opened 2024-04-03 05:54 UTC by FPlohl

Add support for Norik Octopus SoM & IO-Board (nRF9160).

2024-04-03 06:40 UTC, pfiser commented on boards/norik/octopus_io_board/Kconfig.defconfig
> +# Copyright (c) 2023 Nordic Semiconductor ASA
Can we go with:
Copyright (c) 2024 Norik systems d.o.o.
here?

2024-04-03 06:41 UTC, pfiser commented on boards/norik/octopus_io_board/Kconfig.norik_octopus_io_board
> +# Copyright (c) 2024 Norik Systems
Can we go with:
Copyright (c) 2024 Norik systems d.o.o.
here?

2024-04-03 06:41 UTC, pfiser commented on boards/norik/octopus_io_board/board.cmake
> +include(${ZEPHYR_BASE}/boards/common/jlink.board.cmake)
Can we add new-line here?

2024-04-03 06:41 UTC, pfiser commented on boards/norik/octopus_io_board/board.cmake
> +# Copyright (c) 2023 Nordic Semiconductor ASA
Can we go with:
Copyright (c) 2024 Norik systems d.o.o.
here?

2024-04-03 06:43 UTC, pfiser commented on boards/norik/octopus_io_board/doc/img/Norik_Octopus_IO-Board_block_diagram.png
Can you move "Octopus SoM" label into the SoM block?

Same goes for GPS uFL and LTE uFL

2024-04-03 06:45 UTC, pfiser commented on boards/norik/octopus_io_board/doc/index.rst
> +* Dedicated ADC, GPIO, I2C, SPI and UARTE pins for expansion
UARTE? Or just UART?

2024-04-03 06:46 UTC, pfiser commented on boards/norik/octopus_io_board/doc/index.rst
> +* Nano SIM card connector
drop card, just Nano SIM connector?

2024-04-03 06:48 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common-pinctrl.dtsi
> + * Copyright (c) 2022 Nordic Semiconductor
Can we go with:
Copyright (c) 2024 Norik systems d.o.o.
here?

2024-04-03 06:48 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common-pinctrl.dtsi
> +    i2c0_default: i2c0_default {
identation tabs vs spaces?

2024-04-03 06:48 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common-pinctrl.dtsi
> +    i2c1_default: i2c1_default {
identation tabs vs spaces?

2024-04-03 06:48 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common-pinctrl.dtsi
> +};
add new line at the end

2024-04-03 06:49 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common.dtsi
> + * Copyright (c) 2023-2024 Norik Systems
Can we go with:
Copyright (c) 2024 Norik systems d.o.o.
here?

2024-04-03 06:49 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common.dtsi
> +	   };
identation?

2024-04-03 06:50 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common.dtsi
> +   /* These aliases are provided for compatibility with samples */
Identation (whole block)?

2024-04-03 06:51 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common.dtsi
> +//		int1-gpios = <&gpio0 12 0>;
Drop int1-gpios if not used?

2024-04-03 06:51 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common.dtsi
> +
Why space above and bellow?

2024-04-03 06:51 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common.dtsi
> +	w25q64: w25q64@0 {
add space above?

2024-04-03 06:51 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common.dtsi
> +
Remove extra space?

2024-04-03 06:52 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_defconfig
> +# SPDX-License-Identifier: Apache-2.0
Do we need to add copyright here?

2024-04-03 06:52 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_nrf9160.dts
> + * Copyright (c) 2023-2024 Norik Systems
Can we go with:
Copyright (c) 2024 Norik systems d.o.o.
here?

2024-04-03 06:53 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_nrf9160.yaml
> +identifier: norik_octopus_io_boardnrf9160
Is it boardnrf9160 or board_nrf9160?

2024-04-03 06:53 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_nrf9160.yaml
> +vendor: norik
Add new line at the end?

2024-04-03 06:53 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_nrf9160_ns.dts
> + * Copyright (c) 2023-2024 Norik Systems
Can we go with:
Copyright (c) 2024 Norik systems d.o.o.
here?

2024-04-03 06:53 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_nrf9160_ns.dts
> +
new line here?

2024-04-03 06:54 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_nrf9160_ns_defconfig
> +CONFIG_TRUSTED_EXECUTION_NONSECURE=y
add new line here

2024-04-03 06:54 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_nrf9160_ns_defconfig
> +# SPDX-License-Identifier: Apache-2.0
Copyright missing or not?

2024-04-03 06:54 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_nrf9160_partition_conf.dtsi
> + * Copyright (c) 2023-2024 Norik Systems
Can we go with:
Copyright (c) 2024 Norik systems d.o.o.
here?

2024-04-03 06:55 UTC, pfiser commented on boards/norik/octopus_som/Kconfig.defconfig
> +# Copyright (c) 2023 Nordic Semiconductor ASA
Can we go with:
Copyright (c) 2024 Norik systems d.o.o.
here?

2024-04-03 06:55 UTC, pfiser commented on boards/norik/octopus_som/Kconfig.norik_octopus_som
> +# Copyright (c) 2024 Norik Systems
Can we go with:
Copyright (c) 2024 Norik systems d.o.o.
here?

2024-04-03 06:55 UTC, pfiser commented on boards/norik/octopus_som/board.cmake
> +include(${ZEPHYR_BASE}/boards/common/jlink.board.cmake)
New line here

2024-04-03 06:55 UTC, pfiser commented on boards/norik/octopus_som/board.cmake
> +# Copyright (c) 2023 Nordic Semiconductor ASA
Can we go with:
Copyright (c) 2024 Norik systems d.o.o.
here?

2024-04-03 06:58 UTC, pfiser commented on boards/norik/octopus_som/doc/index.rst
> +
Maybe too much empty lines here?

2024-04-03 06:58 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_common-pinctrl.dtsi
> + * Copyright (c) 2022 Nordic Semiconductor
Use same copyright for all files in this PR?

2024-04-03 06:58 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_common-pinctrl.dtsi
> +    i2c0_default: i2c0_default {
identation?

2024-04-03 06:59 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_common-pinctrl.dtsi
> +    i2c1_default: i2c1_default {
identation

2024-04-03 06:59 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_common-pinctrl.dtsi
> +};
new line add

2024-04-03 06:59 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_common.dtsi
> + * Copyright (c) 2023-2024 Norik Systems
same copyright

2024-04-03 06:59 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_common.dtsi
> +   /* These aliases are provided for compatibility with samples */
identation

2024-04-03 07:00 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_common.dtsi
> +&adc {
identation adc, gpiote, gpio0, uart0 blocks

2024-04-03 07:00 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_common.dtsi
> +//		int1-gpios = <&gpio0 12 0>;
drop if not used?

2024-04-03 07:01 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_nrf9160.dts
> +
new line

2024-04-03 07:01 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_nrf9160.yaml
> +vendor: norik
new line

2024-04-03 07:01 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_nrf9160_ns.dts
> + * Copyright (c) 2023-2024 Norik Systems
unified copyright

2024-04-03 07:02 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_nrf9160_ns.dts
> +
new line

2024-04-03 07:02 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_nrf9160_ns.yaml
> +
new line

2024-04-03 07:02 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_nrf9160_partition_conf.dtsi
> + * Copyright (c) 2023-2024 Norik Systems
unified copyright

2024-04-03 07:04 UTC, pfiser requested changes
A lot of nodes in device-tree seem to be duplicated?

Is it possible to define it once and include it later?

For example, why are there two "spi3" nodes duplicated?

2024-04-03 07:25 UTC, UKosale commented on boards/norik/octopus_io_board/doc/img/Norik_Octopus_IO-Board_front.png
The black frame around the image could be trimmed

2024-04-03 07:28 UTC, UKosale commented on boards/norik/octopus_som/doc/img/Norik Octopus Som back.png
The black frame around the image could be trimmed.

2024-04-03 07:28 UTC, UKosale commented on boards/norik/octopus_som/doc/img/Norik_Octopus_Som_front.png
The black frame around the image could be trimmed.

2024-04-03 07:36 UTC, FPlohl commented on boards/norik/octopus_io_board/doc/index.rst
> +* Dedicated ADC, GPIO, I2C, SPI and UARTE pins for expansion
nRF9160 contains UARTE: https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf9160%2Fuarte.html

2024-04-03 07:51 UTC, FPlohl commented on boards/norik/octopus_io_board/norik_octopus_io_board_defconfig
> +# SPDX-License-Identifier: Apache-2.0
Others didn't add the copyright in this file and it's really similar if not the same for boards with the same MCU: 

https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/nordic/nrf9160dk/nrf9160dk_nrf9160_defconfig
https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/actinius/icarus_som/actinius_icarus_som_defconfig
https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/circuitdojo/feather/circuitdojo_feather_nrf9160_defconfig

Didn't know if I should add it or not

2024-04-03 07:54 UTC, FPlohl commented on boards/norik/octopus_io_board/norik_octopus_io_board_nrf9160.yaml
> +identifier: norik_octopus_io_boardnrf9160
Typo. Should be: norik_octopus_io_board/nrf9160

2024-04-03 08:27 UTC, FPlohl commented on boards/norik/octopus_som/norik_octopus_som_nrf9160.dts
> +
Between line 18 and 19?

2024-04-03 08:32 UTC, FPlohl commented on boards/norik/octopus_io_board/norik_octopus_io_board_common.dtsi
> +
Line 160?

2024-04-03 08:36 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common.dtsi
> +
161

2024-04-03 08:36 UTC, FPlohl commented on boards/norik/octopus_io_board/board.cmake
> +include(${ZEPHYR_BASE}/boards/common/jlink.board.cmake)
Between 4 & 5 or after 6?

2024-04-03 08:37 UTC, pfiser commented on boards/norik/octopus_io_board/board.cmake
> +include(${ZEPHYR_BASE}/boards/common/jlink.board.cmake)
after 6

2024-04-05 06:43 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_nrf9160_ns.dts
> +
I still have red minus sign here :) check again, maybe some hidden char?

2024-04-05 06:45 UTC, pfiser commented on boards/norik/octopus_som/norik_octopus_som_common.dtsi
> +	simselect-controller{
Add space between controller and { bracket.

2024-04-05 06:46 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common.dtsi
> +&flash0 {
flash0 node seems to be duplicated between Board and SoM.... can we try to get rid of one?

2024-04-05 06:46 UTC, pfiser commented on boards/norik/octopus_io_board/norik_octopus_io_board_common.dtsi
> +	reserved-memory {
Same here... reserved-memory seems duplicated?

2024-06-10 08:58 UTC, FPlohl commented
Requesting review @pfiser @andrejpicej

2024-06-10 13:48 UTC, pfiser commented
Can you do before my review:
git fetch origin/main
git rebase main
and then squash commits into logic units

2024-06-11 09:59 UTC, pfiser requested changes
We decided to open PR #2 instead. Closing this one.

2024-06-11 10:00 UTC, closed without merging